id: IB3675564
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:49:46+00:00'
last_modified: '2022-06-07T20:41:00.527648+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017030
  title: ལྷ་བབས་མཆོད་རྟེན་ཆེན་མོའི་དཀར་ཆག་པདྨ་སྟོང་ལྡན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D565:
      image_group_id: I00EGS1017032
      title: ''
      total_pages: 278
      order: 1
      base_file: D565.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
